---
title: "About Page Draft"
author: "Stephanie Cheng"
date: "2/28/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#### About the Topic
As an emerging product and UI/UX designer coming from an unconventional design
background, I have recently been interested in taking a deeper dive into better
understanding what the design field quantitatively looks like. I am particularly
interested in learning more about what the demographic of current designers are,
how its have changed over the last two years, and how it correlates with the
general spread of companies and industries in the US.

This project aims to hopefully elucidate design career trends for anyone
interested in entering the field, already in the field, or curious about design.

#### About the Data
The Design Census data was collected by The American Institute of Graphic Arts
(AIGA) most recently in 2017 and 2019. The Design Census was a survey that was
circulated in the design community and open to public for 5 weeks. The raw csv
data files were downloaded from the respective Design Census websites, which can
be found [here for the 2019 data](https://designcensus.org/) and [here for the
2017 data](http://designcensus2017.aiga.org/).

The data set on US companies was from the Open Data 500 Project, which is the
first comprehensive study of US companies that use open government data
conducted by the GovLab of New York University. The raw csv data files were
downloaded from the Open Data 500 website, which can be found
[here](https://www.opendata500.com/us/).

In order to make sense of the zip codes from the aforementioned data sets, a US
zip codes data set from SimpleMaps was used to configure zip codes to states and
cities. The zip codes dataset can be found
[here](https://simplemaps.com/data/us-zips).

#### Progress and Plans
So far, I have cleaned up the variable/column names for the design census data
sets as they were quite messy and had uninformative variable/column names
initially. Although the data between the 2017 and 2019 surveys didn't match up
exactly, I tried to be as consistent as possible between the two for greater
ease in data analysis in the future.

I have done some preliminary analysis of the distribution of designers and
companies by state to ensure that there is a wide enough distribution for
analysis. However, I still need to flesh out how exactly I want to analyze the
relationship between the spread of companies and designers. There are a lot of
variables from the design census data sets that I need to parse through and
figure out which specific aspects are the most informative and will be the most
interesting to analyze.

#### About Me
I am a senior concentrating in Neuroscience with a secondary in Mind, Brain, and
Behavior. 

My design porftolio can be found [here](http://www.stephcheng.com) and the github repo to
this project can be found
[here](https://github.com/swcg1/gov1005-final_project).
