---
title: "Initial Data Processing"
author: "Stephanie Cheng"
date: "3/6/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(dplyr)
library(ggplot2)
library(readr)
library(janitor)
```

```{r initial analysis, echo=FALSE}

# join zip code and state names to census data

census_2019_by_state <- census_2019 %>%
  left_join(us_zips, by = c("zip_code" = "zip")) %>%
  select(zip_code, state_name) %>%
  na.omit() %>%
  group_by(state_name) %>%
  count() %>%
  ggplot(aes(n, state_name)) +
  geom_point() +
    labs(title = "Distribution of Designers by State in 2019",
       x = "Number of designers",
       y = "State")

census_2017_by_state <- census_2017 %>%
  left_join(us_zips, by = c("zip_code" = "zip")) %>%
  select(zip_code, state_name) %>%
  na.omit() %>%
  group_by(state_name) %>%
  count() %>%
  ggplot(aes(n, state_name)) +
  geom_point() +
  labs(title = "Distribution of Designers by State in 2017",
       x = "Number of designers",
       y = "State")

us_companies_by_state <- us_companies %>%
  left_join(us_zips, by = c("zip_code" = "zip")) %>%
  select(zip_code, state_name) %>%
  na.omit() %>%
  group_by(state_name) %>%
  count() %>%
  ggplot(aes(n, state_name)) +
  geom_point() +
  labs(title = "US Companies Distribution by State",
       x = "Number of companies",
       y = "State")

census_2019_by_state
census_2017_by_state
us_companies_by_state
```
